name: Prepare Python Environment

runs:
  using: "composite"

  steps:

    - name: Setup Python 3.11 version
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install poetry
      shell: bash
      run: |
        pip install poetry==1.8.3

    - name: Install AWS Cli
      shell: bash
      run: |
        pip install poetry==1.8.3 awscli

    - name: Install dependencies
      shell: bash
      run: poetry install
